# Generated by Django 4.0.5 on 2022-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='students_number',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='students.subject', verbose_name='Предмети'),
        ),
    ]
